// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using WebTrader.Context;

#nullable disable

namespace WebTrader.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220425021201_insert_tipo_produto")]
    partial class insert_tipo_produto
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WebTrader.Models.Categoria", b =>
                {
                    b.Property<int>("CategoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoriaId"), 1L, 1);

                    b.Property<string>("CategoriaNome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.HasKey("CategoriaId");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("WebTrader.Models.Dominio.T_Endereco", b =>
                {
                    b.Property<int>("IdEndereco")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEndereco"), 1L, 1);

                    b.Property<bool>("Ativo")
                        .HasMaxLength(1)
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<string>("Complemento")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("NVARCHAR2(2)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<int>("NumeroCasa")
                        .HasMaxLength(5)
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("País")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.HasKey("IdEndereco");

                    b.ToTable("T_Endereco");
                });

            modelBuilder.Entity("WebTrader.Models.Lanche", b =>
                {
                    b.Property<int>("LancheId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LancheId"), 1L, 1);

                    b.Property<int>("CategoriaId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("DescricaoCurta")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<string>("DescricaoDetalhada")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<bool>("EmEstoque")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("ImagemThumbnailUrl")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<string>("ImagemUrl")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<bool>("IsLanchePreferido")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("NVARCHAR2(80)");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("LancheId");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Lanches");
                });

            modelBuilder.Entity("WebTrader.Models.T_Contato", b =>
                {
                    b.Property<int>("IdContato")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdContato"), 1L, 1);

                    b.Property<bool>("Ativo")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("DescricaoContato")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("NVARCHAR2(25)");

                    b.Property<int?>("TipoContatoIdTipoContato")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("IdContato");

                    b.HasIndex("TipoContatoIdTipoContato");

                    b.ToTable("T_Contato");
                });

            modelBuilder.Entity("WebTrader.Models.T_Proposta_Negociacao", b =>
                {
                    b.Property<int>("IdPropostaNegociacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPropostaNegociacao"), 1L, 1);

                    b.Property<string>("DescricaoCurta")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<string>("Empresa")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<string>("ImagemThumbnailUrl")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<string>("Marca")
                        .HasMaxLength(25)
                        .HasColumnType("NVARCHAR2(25)");

                    b.Property<string>("PermiteUsado")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("NVARCHAR2(3)");

                    b.Property<decimal>("Preco")
                        .HasMaxLength(25)
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<string>("Produto")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<int>("Quantidade")
                        .HasMaxLength(5)
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("TipoProdutoIdTipoProduto")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("UsuarioIdUsuario")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("IdPropostaNegociacao");

                    b.HasIndex("TipoProdutoIdTipoProduto");

                    b.HasIndex("UsuarioIdUsuario");

                    b.ToTable("T_Proposta_Negociacao");
                });

            modelBuilder.Entity("WebTrader.Models.T_Tipo_Contato", b =>
                {
                    b.Property<int>("IdTipoContato")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipoContato"), 1L, 1);

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.HasKey("IdTipoContato");

                    b.ToTable("T_Tipo_Contato");
                });

            modelBuilder.Entity("WebTrader.Models.T_Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"), 1L, 1);

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<int?>("ContatosIdContato")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("EnderecosIdEndereco")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Idade")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<string>("RG")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.HasKey("IdUsuario");

                    b.HasIndex("ContatosIdContato");

                    b.HasIndex("EnderecosIdEndereco");

                    b.ToTable("T_Usuario");
                });

            modelBuilder.Entity("WebTrader.Models.Tipo.T_Tipo_Produto", b =>
                {
                    b.Property<int>("IdTipoProduto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipoProduto"), 1L, 1);

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.HasKey("IdTipoProduto");

                    b.ToTable("T_Tipo_Produto");
                });

            modelBuilder.Entity("WebTrader.Models.Lanche", b =>
                {
                    b.HasOne("WebTrader.Models.Categoria", "Categoria")
                        .WithMany("Lanches")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("WebTrader.Models.T_Contato", b =>
                {
                    b.HasOne("WebTrader.Models.T_Tipo_Contato", "TipoContato")
                        .WithMany("Contato")
                        .HasForeignKey("TipoContatoIdTipoContato");

                    b.Navigation("TipoContato");
                });

            modelBuilder.Entity("WebTrader.Models.T_Proposta_Negociacao", b =>
                {
                    b.HasOne("WebTrader.Models.Tipo.T_Tipo_Produto", "TipoProduto")
                        .WithMany("PropostaNegociacao")
                        .HasForeignKey("TipoProdutoIdTipoProduto");

                    b.HasOne("WebTrader.Models.T_Usuario", "Usuario")
                        .WithMany("PropostaNegociacao")
                        .HasForeignKey("UsuarioIdUsuario");

                    b.Navigation("TipoProduto");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("WebTrader.Models.T_Usuario", b =>
                {
                    b.HasOne("WebTrader.Models.T_Contato", "Contatos")
                        .WithMany("Usuario")
                        .HasForeignKey("ContatosIdContato");

                    b.HasOne("WebTrader.Models.Dominio.T_Endereco", "Enderecos")
                        .WithMany("Usuario")
                        .HasForeignKey("EnderecosIdEndereco");

                    b.Navigation("Contatos");

                    b.Navigation("Enderecos");
                });

            modelBuilder.Entity("WebTrader.Models.Categoria", b =>
                {
                    b.Navigation("Lanches");
                });

            modelBuilder.Entity("WebTrader.Models.Dominio.T_Endereco", b =>
                {
                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("WebTrader.Models.T_Contato", b =>
                {
                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("WebTrader.Models.T_Tipo_Contato", b =>
                {
                    b.Navigation("Contato");
                });

            modelBuilder.Entity("WebTrader.Models.T_Usuario", b =>
                {
                    b.Navigation("PropostaNegociacao");
                });

            modelBuilder.Entity("WebTrader.Models.Tipo.T_Tipo_Produto", b =>
                {
                    b.Navigation("PropostaNegociacao");
                });
#pragma warning restore 612, 618
        }
    }
}
